FROM wpilib/debian-base:trixie

RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        curl \
        gnupg \
        ninja-build \
        build-essential \
        libtbb-dev=2022.1.0-1+deb13u1 && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g pnpm@11 && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]

